# Generated by Django 3.1 on 2021-07-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_thicknessmeasurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thicknessmeasurement',
            options={'default_permissions': (), 'get_latest_by': 'timestamp', 'ordering': ['timestamp'], 'verbose_name': 'thickness measurement', 'verbose_name_plural': 'thickness measurements'},
        ),
    ]
