# Generated by Django 3.1 on 2021-09-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0006_auto_20210728_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('current', models.DecimalField(decimal_places=5, help_text='mA', max_digits=10, verbose_name='Measuring current')),
                ('thickness', models.DecimalField(decimal_places=5, help_text='µm', max_digits=10, verbose_name='Samples thickness')),
                ('t1', models.DecimalField(decimal_places=2, help_text='K', max_digits=7, verbose_name='Starting Temperature')),
                ('t2', models.DecimalField(blank=True, decimal_places=2, help_text='K', max_digits=7, verbose_name='Final Temperature')),
            ],
            options={
                'verbose_name': 'hall measurement',
                'verbose_name_plural': 'hall measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
    ]
