# Generated by Django 3.1 on 2021-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_hallmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallmeasurement',
            name='t2',
            field=models.DecimalField(decimal_places=2, help_text='K', max_digits=7, verbose_name='Final Temperature'),
        ),
    ]
