# Generated by Django 3.1 on 2021-09-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0008_auto_20210916_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamanMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='K', max_digits=7, verbose_name='temperature')),
                ('wave', models.CharField(choices=[('other', 'other'), ('one', '325 nm'), ('two', '442 nm'), ('three', '532 nm'), ('four', '633 nm'), ('five', '785 nm')], default='other', max_length=20, verbose_name='excitation wavelength')),
                ('lines', models.CharField(choices=[('other', 'other'), ('one', '600 per mm'), ('two', '1200 per mm'), ('three', '1800 per mm'), ('four', '2400 per mm')], default='other', max_length=20, verbose_name='number of lines')),
            ],
            options={
                'verbose_name': 'raman measurement',
                'verbose_name_plural': 'raman measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
    ]
