# Generated by Django 3.1 on 2021-09-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0009_ramanmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTIRMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('set', models.CharField(choices=[('c', 'c'), ('n', 'n'), ('o', 'o'), ('other', 'other')], default='c', max_length=20, verbose_name='parameter set')),
                ('reference', models.CharField(max_length=100, verbose_name='reference sample')),
                ('carrier', models.CharField(help_text='Atoms per cubic millimeter', max_length=20, verbose_name='charge carrier concentration')),
                ('defect', models.CharField(max_length=20, verbose_name='defect concentration')),
                ('file', models.TextField(blank=True, verbose_name='Name of datafile')),
            ],
            options={
                'verbose_name': 'FTIR measurement',
                'verbose_name_plural': 'FTIR measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
    ]
