# Generated by Django 3.1 on 2021-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_ftirmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramanmeasurement',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile'),
        ),
        migrations.AlterField(
            model_name='ftirmeasurement',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile'),
        ),
    ]
