# Generated by Django 3.1 on 2021-09-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0011_auto_20210917_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('wave', models.CharField(max_length=50, verbose_name='excitation wavelength')),
                ('t1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='starting temperature')),
                ('t2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='final temperature')),
                ('postiton', models.TextField(blank=True, verbose_name='Position')),
                ('detector', models.CharField(choices=[('ccd', 'CCD'), ('iccd', 'iCCD'), ('r3896', 'R3896'), ('irpmt', 'IR-PMT'), ('apd', 'APD/SPCM'), ('other', 'other')], default='ccd', max_length=30, verbose_name='Detector')),
            ],
            options={
                'verbose_name': 'PL measurement',
                'verbose_name_plural': 'PL measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
        migrations.AlterField(
            model_name='ftirmeasurement',
            name='set',
            field=models.CharField(choices=[('c', 'C'), ('n', 'N'), ('o', 'O'), ('other', 'other')], default='c', max_length=20, verbose_name='parameter set'),
        ),
    ]
