# Generated by Django 3.1 on 2021-09-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0012_auto_20210917_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPSMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('resin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Resolution in direction')),
                ('respar', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Resolution parallel to direction')),
                ('laser', models.CharField(choices=[('one', '830'), ('two', '660'), ('other', 'other')], default='one', max_length=20, verbose_name='laser')),
                ('diff', models.CharField(max_length=50, verbose_name='difference in laser power')),
                ('gain', models.CharField(max_length=50, verbose_name='Gain LP/LPS')),
                ('file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile')),
            ],
            options={
                'verbose_name': 'LPS measurement',
                'verbose_name_plural': 'LPS measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
        migrations.AddField(
            model_name='hallmeasurement',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile'),
        ),
        migrations.AddField(
            model_name='plmeasurement',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile'),
        ),
    ]
