# Generated by Django 3.1 on 2021-09-17 20:15

from django.db import migrations, models
import django.db.models.deletion
import jb_common.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0013_auto_20210917_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='FRTMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('distance', models.CharField(max_length=50, verbose_name='Distance of points')),
                ('lines', jb_common.model_fields.FloatQuantityField(blank=True, null=True, verbose_name='Number of lines')),
                ('rau', models.CharField(blank=True, max_length=100, null=True, verbose_name='roughness')),
                ('file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile')),
            ],
            options={
                'verbose_name': 'FRT measurement',
                'verbose_name_plural': 'FRT measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
    ]
