# Generated by Django 3.1 on 2021-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_frtmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plmeasurement',
            name='detector',
            field=models.CharField(choices=[('ccd', 'CCD'), ('iccd', 'iCCD'), ('r3896', 'R3896'), ('irpmt', 'IR-PMT'), ('apd', 'APD/SPCM'), ('other', 'other')], default='ccd', max_length=30, verbose_name='detector'),
        ),
        migrations.AlterField(
            model_name='plmeasurement',
            name='postiton',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='position'),
        ),
    ]
