# Generated by Django 3.1 on 2021-10-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0016_photoluminescencemeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoluminescencemeasurement',
            name='detector',
            field=models.CharField(choices=[('ccd', 'CCD'), ('iccd', 'iCCD'), ('r3896', 'R3896'), ('irpmt', 'IR-PMT'), ('apd', 'APD,SPCM'), ('other', 'other')], default='ccd', max_length=30, verbose_name='detector'),
        ),
    ]
