# Generated by Django 3.1 on 2021-10-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0018_auto_20211010_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PLMeasurement',
        ),
    ]
