# Generated by Django 3.1 on 2021-10-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0019_delete_plmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('value', models.CharField(max_length=50, verbose_name='Resulting value')),
                ('pa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paramter 1')),
                ('para', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paramter 2')),
                ('file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile')),
            ],
            options={
                'verbose_name': 'any measurement',
                'verbose_name_plural': 'any measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
    ]
