# Generated by Django 3.1 on 2021-10-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0020_anymeasurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoluminescenceMeasurement',
        ),
    ]
