# Generated by Django 3.1 on 2021-10-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
        ('institute', '0021_delete_photoluminescencemeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLMeasurement',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('length', models.CharField(max_length=50, verbose_name='excitation wavelength')),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='starting temperature')),
                ('beta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ending temperature')),
                ('posi', models.CharField(blank=True, max_length=50, null=True, verbose_name='position')),
                ('method', models.CharField(choices=[('one', 'CCD'), ('two', 'iCCD'), ('three', 'R3896'), ('four', 'IR-PMT'), ('five', 'APD-SPCM'), ('other', 'other')], default='one', max_length=50, verbose_name='detector')),
                ('file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of datafile')),
            ],
            options={
                'verbose_name': 'pl measurement',
                'verbose_name_plural': 'pl measurements',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'abstract': False,
                'default_permissions': (),
            },
            bases=('samples.process',),
        ),
    ]
