# Generated by Django 3.1 on 2021-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0023_auto_20211016_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='thicknessmeasurement',
            name='doping',
            field=models.CharField(choices=[('p', 'p'), ('n', 'n'), ('none', 'none')], default='none', max_length=30, verbose_name='doping'),
        ),
    ]
