# Generated by Django 3.1 on 2021-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0024_thicknessmeasurement_doping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpsmeasurement',
            name='laser',
            field=models.CharField(choices=[('one', '830 nm'), ('two', '660 nm'), ('other', 'other')], default='one', max_length=20, verbose_name='laser'),
        ),
    ]
