# Generated by Django 3.1 on 2021-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0027_auto_20211018_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thicknessmeasurement',
            name='thickness',
            field=models.DecimalField(decimal_places=2, help_text='<span>cm</span>', max_digits=7, verbose_name='thicknes'),
        ),
    ]
