# Generated by Django 3.1 on 2021-10-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0030_auto_20211018_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftirmeasurement',
            name='carrier',
            field=models.CharField(help_text='Charge carriers /  cm<sup>3</sup>', max_length=20, verbose_name='charge carrier concentration'),
        ),
        migrations.AlterField(
            model_name='ftirmeasurement',
            name='defect',
            field=models.CharField(help_text='Defects / cm<sup>3</sup>', max_length=20, verbose_name='defect concentration'),
        ),
    ]
