# Generated by Django 3.1 on 2021-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0031_auto_20211018_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plmeasurement',
            name='alpha',
            field=models.DecimalField(decimal_places=2, help_text='K', max_digits=7, verbose_name='starting temperature'),
        ),
        migrations.AlterField(
            model_name='plmeasurement',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='K', max_digits=7, null=True, verbose_name='ending temperature'),
        ),
    ]
