# Generated by Django 3.1 on 2021-10-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0033_auto_20211022_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrate',
            name='doping',
            field=models.CharField(choices=[('none', 'none'), ('p', 'p'), ('n', 'n')], default='none', max_length=30, verbose_name='doping'),
        ),
    ]
