# Generated by Django 3.1 on 2021-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0034_substrate_doping'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrate',
            name='dopant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dopant'),
        ),
        migrations.AddField(
            model_name='substrate',
            name='size',
            field=models.CharField(blank=True, help_text='length x width x height', max_length=120, null=True, verbose_name='size'),
        ),
    ]
